/* SQLCraft — 12-week curriculum */

const weekData = [
  { w:1, phase:1, ph:'ph1', badge:'badge-ph1', label:'Foundations', title:'How databases work & first queries', time:'5–6h', topics:['What is a relational database — tables, rows, columns','Installing PostgreSQL or using DB Fiddle online','SELECT, FROM — retrieve every column and specific columns','WHERE — filter rows by condition','Comparison operators: =, !=, >, <, >=, <=','ORDER BY ASC / DESC','LIMIT — control how many rows come back'], del:'Write 10 queries on the Northwind sample database using SELECT, WHERE, ORDER BY.' },
  { w:2, phase:1, ph:'ph1', badge:'badge-ph1', label:'Foundations', title:'Filtering, nulls & column logic', time:'5–6h', topics:['AND, OR, NOT — combining conditions','IN and BETWEEN — compact filtering','IS NULL / IS NOT NULL — handling missing data','COALESCE — replace nulls with a default','Column aliases with AS','String functions: UPPER, LOWER, LENGTH, TRIM','LIKE — pattern matching with % and _'], del:'20-query drill: answer 20 business questions on sample data. No peeking at syntax.' },
  { w:3, phase:1, ph:'ph1', badge:'badge-ph1', label:'Foundations', title:'Aggregation & grouping', time:'6–7h', topics:['COUNT(*) vs COUNT(column) — the important difference','SUM, AVG, MIN, MAX','GROUP BY — aggregate per category','HAVING — filter groups after aggregation','Difference between WHERE and HAVING','Combining GROUP BY with ORDER BY','COUNT(DISTINCT col) — count unique values'], del:'Answer 10 business questions using GROUP BY: sales by region, orders per customer, etc.' },
  { w:4, phase:1, ph:'ph1', badge:'badge-ph1', label:'Foundations', title:'Foundations review + first project', time:'6–7h', topics:['Review all weeks 1–3 concepts','Work through 15 LeetCode Easy SQL problems','Identify weak spots — re-drill them','Set up a GitHub account to save your work','Write a "top 10 customers by revenue" query from scratch','Write a "monthly sales trend" query','Document and comment your queries clearly'], del:'Solve all LeetCode SQL Easy problems. Push your query files to GitHub.' },
  { w:5, phase:2, ph:'ph2', badge:'badge-ph2', label:'Core analyst', title:'JOINs — combining tables', time:'7–8h', topics:['Why data is split across tables (normalisation basics)','INNER JOIN — only matching rows','LEFT JOIN — all left rows, NULLs where no match','RIGHT JOIN — and when to avoid it','FULL OUTER JOIN — all rows from both sides','Joining on multiple columns','Chaining 3 or more tables together'], del:'Write 10 queries using JOINs: customers + orders, employees + sales, products + categories.' },
  { w:6, phase:2, ph:'ph2', badge:'badge-ph2', label:'Core analyst', title:'CASE WHEN + date logic', time:'6–7h', topics:['CASE WHEN THEN ELSE END — conditional columns','Bucketing numeric values into categories','CASE inside aggregate functions (pivoting)','Date functions: YEAR, MONTH, DAY, DATEPART','DATEDIFF — days between two dates','DATEADD — shifting dates forward/back','Extracting week numbers and quarters'], del:'Build a customer segmentation query: bucket customers by spend into Low/Mid/High tiers.' },
  { w:7, phase:2, ph:'ph2', badge:'badge-ph2', label:'Core analyst', title:'Subqueries & query structure', time:'7–8h', topics:['Subquery in WHERE — filter using another query','Subquery in FROM — use a query as a table','Subquery in SELECT — scalar subqueries','Correlated vs non-correlated subqueries','EXISTS and NOT EXISTS','When to prefer a JOIN over a subquery','Query execution order: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY'], del:'Rewrite 5 JOIN queries using subqueries and vice versa. Compare readability.' },
  { w:8, phase:2, ph:'ph2', badge:'badge-ph2', label:'Core analyst', title:'Core skills review + project', time:'7–8h', topics:['LeetCode Medium SQL — aim for 20 problems','Review: JOINs, CASE WHEN, subqueries','Practice explaining your queries out loud','Pick a public dataset (e.g. Kaggle NYC Taxi)','Write 8 business questions about the dataset','Answer them all in SQL','Push polished queries to GitHub with a README'], del:'Completed project #1 on GitHub: public dataset analysed with 8 SQL queries + writeup.' },
  { w:9, phase:3, ph:'ph3', badge:'badge-ph3', label:'Advanced', title:'CTEs — clean multi-step queries', time:'8h', topics:['WITH clause syntax — writing your first CTE','Why CTEs beat nested subqueries for readability','Chaining multiple CTEs together','Recursive CTEs — traversing hierarchies','Refactor a complex query into CTEs step by step','Naming conventions for CTE clarity','When NOT to use CTEs (performance considerations)'], del:'Take 3 of your hardest queries from weeks 5–8 and rewrite them using CTEs.' },
  { w:10, phase:3, ph:'ph3', badge:'badge-ph3', label:'Advanced', title:'Window functions', time:'8–9h', topics:['OVER() clause — what makes a window function','PARTITION BY — groups without collapsing rows','ROW_NUMBER, RANK, DENSE_RANK — row numbering','LAG and LEAD — compare with previous/next row','Running totals: SUM() OVER (ORDER BY date)','Moving averages: AVG() OVER (ROWS BETWEEN ...)','Top-N per group pattern — the classic interview question'], del:'Solve 10 window function problems on LeetCode and StrataScratch. Focus on top-N per group.' },
  { w:11, phase:3, ph:'ph3', badge:'badge-ph3', label:'Advanced', title:'Performance, UNION & data modelling', time:'7–8h', topics:['UNION vs UNION ALL — and when each applies','SELF JOIN — comparing rows in the same table','EXPLAIN / query plan — reading what the DB does','What indexes are and why they speed queries up','Identifying slow queries and common causes','Star schema: fact tables vs dimension tables','Intro to data warehousing concepts (BigQuery / Snowflake)'], del:'Run EXPLAIN on 5 of your queries. Identify the slowest step and propose an index.' },
  { w:12, phase:4, ph:'ph4', badge:'badge-ph4', label:'Job ready', title:'Interview prep + portfolio project', time:'8–10h', topics:['LeetCode Hard SQL — target 10 problems','StrataScratch: solve 5 real company interview questions','Practice live coding: write queries while explaining aloud','Build portfolio project #2 on a dataset you care about','Write a clean README with business context + findings','Polish GitHub: consistent formatting, comments, descriptions','Prepare answers to: "walk me through a complex query you wrote"'], del:'Portfolio live on GitHub: 2 projects, 15+ queries, clean READMEs. Apply to 3 analyst roles.' },
];