/* SQLCraft — DB schema + 36 exercises */

const DB_SQL = `
CREATE TABLE customers (id INTEGER PRIMARY KEY, name TEXT, email TEXT, country TEXT, created_at TEXT);
CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT, category TEXT, price REAL, stock INTEGER);
CREATE TABLE orders (id INTEGER PRIMARY KEY, customer_id INTEGER, order_date TEXT, total REAL, status TEXT);
CREATE TABLE order_items (id INTEGER PRIMARY KEY, order_id INTEGER, product_id INTEGER, qty INTEGER, unit_price REAL);
CREATE TABLE employees (id INTEGER PRIMARY KEY, name TEXT, department TEXT, salary REAL, hire_date TEXT, manager_id INTEGER);
CREATE TABLE sales (id INTEGER PRIMARY KEY, employee_id INTEGER, region TEXT, amount REAL, sale_date TEXT);

INSERT INTO customers VALUES
(1,'Alice Chen','alice@email.com','Australia','2023-01-15'),
(2,'Bob Smith','bob@email.com','USA','2023-02-20'),
(3,'Clara Diaz','clara@email.com','Spain','2023-01-08'),
(4,'Dan Park','dan@email.com','Korea','2023-03-12'),
(5,'Eva Mills','eva@email.com','Australia','2023-04-05'),
(6,'Frank Lee','frank@email.com','USA','2023-05-18'),
(7,'Grace Kim','grace@email.com','Korea','2023-06-22'),
(8,'Henry Tan','henry@email.com','Singapore','2023-07-30'),
(9,'Iris Wang','iris@email.com','Australia','2023-08-14'),
(10,'Jack Brown','jack@email.com','UK','2022-12-01');

INSERT INTO products VALUES
(1,'Wireless Headphones','Electronics',89.99,45),
(2,'Mechanical Keyboard','Electronics',129.99,30),
(3,'Desk Lamp','Furniture',34.99,80),
(4,'Coffee Mug','Kitchen',12.99,200),
(5,'Notebook','Stationery',8.99,500),
(6,'Monitor Stand','Furniture',59.99,25),
(7,'USB Hub','Electronics',24.99,60),
(8,'Standing Desk','Furniture',399.99,10),
(9,'Pen Set','Stationery',15.99,300),
(10,'Espresso Machine','Kitchen',249.99,15);

INSERT INTO orders VALUES
(1,1,'2024-01-05',119.98,'completed'),
(2,2,'2024-01-08',89.99,'completed'),
(3,1,'2024-01-12',34.99,'completed'),
(4,3,'2024-01-15',259.98,'shipped'),
(5,4,'2024-01-18',12.99,'completed'),
(6,5,'2024-01-20',399.99,'completed'),
(7,6,'2024-01-22',499.98,'processing'),
(8,2,'2024-02-01',74.97,'completed'),
(9,7,'2024-02-05',129.99,'completed'),
(10,8,'2024-02-10',59.99,'completed'),
(11,9,'2024-02-14',24.99,'shipped'),
(12,10,'2024-02-18',249.99,'completed'),
(13,1,'2024-03-01',64.97,'completed'),
(14,3,'2024-03-08',399.99,'completed'),
(15,5,'2024-03-15',89.99,'completed');

INSERT INTO order_items VALUES
(1,1,1,1,89.99),(2,1,4,2,12.99),(3,2,1,1,89.99),(4,3,3,1,34.99),
(5,4,2,1,129.99),(6,4,7,2,24.99),(7,5,4,1,12.99),(8,6,8,1,399.99),
(9,7,2,2,129.99),(10,7,7,1,24.99),(11,8,5,3,8.99),(12,8,4,1,12.99),
(13,8,9,2,15.99),(14,9,2,1,129.99),(15,10,6,1,59.99),(16,11,7,1,24.99),
(17,12,10,1,249.99),(18,13,5,2,8.99),(19,13,9,3,15.99),(20,14,8,1,399.99),
(21,15,1,1,89.99);

INSERT INTO employees VALUES
(1,'Sarah Johnson','Sales',75000,'2020-03-15',NULL),
(2,'Mike Torres','Engineering',95000,'2019-07-01',NULL),
(3,'Amy Chen','Sales',68000,'2021-01-20',1),
(4,'David Park','Engineering',110000,'2018-05-10',2),
(5,'Lisa Wang','Marketing',72000,'2021-09-01',NULL),
(6,'Tom Brown','Sales',62000,'2022-02-14',1),
(7,'Nina Patel','Engineering',88000,'2020-11-30',2),
(8,'Carlos Ruiz','Marketing',78000,'2019-04-22',5),
(9,'Emma Wilson','Sales',71000,'2021-06-18',1),
(10,'James Lee','Engineering',92000,'2020-08-05',2);

INSERT INTO sales VALUES
(1,3,'APAC',8500,'2024-01-10'),
(2,6,'AMER',12000,'2024-01-12'),
(3,9,'EMEA',9200,'2024-01-15'),
(4,3,'APAC',7800,'2024-01-20'),
(5,6,'AMER',15000,'2024-02-05'),
(6,9,'EMEA',11000,'2024-02-08'),
(7,3,'APAC',9500,'2024-02-12'),
(8,6,'AMER',8200,'2024-02-18'),
(9,9,'EMEA',13500,'2024-03-01'),
(10,3,'APAC',11000,'2024-03-05'),
(11,6,'AMER',9800,'2024-03-10'),
(12,9,'EMEA',7600,'2024-03-15');
`;

const SCHEMA_INFO = {
  customers: { fields: ['id INT', 'name TEXT', 'email TEXT', 'country TEXT', 'created_at TEXT'] },
  products: { fields: ['id INT', 'name TEXT', 'category TEXT', 'price REAL', 'stock INT'] },
  orders: { fields: ['id INT', 'customer_id INT', 'order_date TEXT', 'total REAL', 'status TEXT'] },
  order_items: { fields: ['id INT', 'order_id INT', 'product_id INT', 'qty INT', 'unit_price REAL'] },
  employees: { fields: ['id INT', 'name TEXT', 'department TEXT', 'salary REAL', 'hire_date TEXT', 'manager_id INT'] },
  sales: { fields: ['id INT', 'employee_id INT', 'region TEXT', 'amount REAL', 'sale_date TEXT'] },
};

const exercises = [
  { id:1, phase:1, week:1, title:'Select all customers', diff:'easy', topic:'SELECT',
    desc:'Retrieve every column from the customers table.',
    tables:['customers'],
    starter:'SELECT * FROM customers;',
    solution:'SELECT * FROM customers;',
    hint:'Use SELECT * to get all columns, then FROM to specify the table.',
    validate: r => r.length === 10 },

  { id:2, phase:1, week:1, title:'Customer names and countries', diff:'easy', topic:'SELECT',
    desc:'Get only the name and country columns from customers.',
    tables:['customers'],
    starter:'SELECT ',
    solution:'SELECT name, country FROM customers;',
    hint:'List the column names you want separated by commas after SELECT.',
    validate: r => r.length===10 && r[0].hasOwnProperty('name') && r[0].hasOwnProperty('country') && !r[0].hasOwnProperty('email') },

  { id:3, phase:1, week:1, title:'Australian customers only', diff:'easy', topic:'WHERE',
    desc:'Find all customers who are from Australia.',
    tables:['customers'],
    starter:'SELECT * FROM customers\nWHERE ',
    solution:"SELECT * FROM customers WHERE country = 'Australia';",
    hint:"Use WHERE country = 'Australia' — text values need single quotes.",
    validate: r => r.length===3 && r.every(x=>x.country==='Australia') },

  { id:4, phase:1, week:2, title:'Products under $50', diff:'easy', topic:'WHERE',
    desc:'List all products with a price less than 50.',
    tables:['products'],
    starter:'SELECT * FROM products\nWHERE ',
    solution:'SELECT * FROM products WHERE price < 50;',
    hint:'Compare price to a number using the < operator. Numbers do not need quotes.',
    validate: r => r.length > 0 && r.every(x => x.price < 50) },

  { id:5, phase:1, week:2, title:'Top 5 most expensive products', diff:'easy', topic:'ORDER BY',
    desc:'Show the 5 most expensive products, most expensive first.',
    tables:['products'],
    starter:'SELECT name, price FROM products\n',
    solution:'SELECT name, price FROM products ORDER BY price DESC LIMIT 5;',
    hint:'ORDER BY price DESC sorts highest first. LIMIT 5 takes only 5 rows.',
    validate: r => r.length===5 && r[0].price >= r[4].price },

  { id:6, phase:1, week:2, title:'Completed orders', diff:'easy', topic:'WHERE',
    desc:"Find all orders with status = 'completed'.",
    tables:['orders'],
    starter:'SELECT * FROM orders\nWHERE ',
    solution:"SELECT * FROM orders WHERE status = 'completed';",
    hint:"Filter on the status column using WHERE status = 'completed'.",
    validate: r => r.length > 0 && r.every(x => x.status === 'completed') },

  { id:7, phase:1, week:3, title:'Count total orders', diff:'easy', topic:'COUNT',
    desc:'How many orders are in the orders table?',
    tables:['orders'],
    starter:'SELECT ',
    solution:'SELECT COUNT(*) AS total_orders FROM orders;',
    hint:'COUNT(*) counts all rows. Use AS to give the result column a name.',
    validate: r => r.length===1 && Object.values(r[0])[0]===15 },

  { id:8, phase:1, week:3, title:'Orders per customer', diff:'easy', topic:'GROUP BY',
    desc:'Count how many orders each customer has placed.',
    tables:['orders'],
    starter:'SELECT customer_id, COUNT(*) AS order_count\nFROM orders\n',
    solution:'SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id ORDER BY order_count DESC;',
    hint:'GROUP BY customer_id groups rows by each customer. Use COUNT(*) to count within each group.',
    validate: r => r.length > 0 && r.every(x => x.hasOwnProperty('order_count')) },

  { id:9, phase:1, week:3, title:'Revenue by product category', diff:'medium', topic:'GROUP BY',
    desc:'Calculate the total revenue (sum of price × stock) for each product category.',
    tables:['products'],
    starter:'SELECT category, \nFROM products\nGROUP BY ',
    solution:'SELECT category, SUM(price * stock) AS total_value FROM products GROUP BY category ORDER BY total_value DESC;',
    hint:'Multiply price * stock to get value per product. SUM() it grouped by category.',
    validate: r => r.length > 0 && r.every(x => x.hasOwnProperty('category')) },

  { id:10, phase:1, week:3, title:'Average salary by department', diff:'medium', topic:'AVG',
    desc:'Find the average salary for each department in the employees table.',
    tables:['employees'],
    starter:'SELECT department, \nFROM employees\nGROUP BY ',
    solution:'SELECT department, AVG(salary) AS avg_salary FROM employees GROUP BY department ORDER BY avg_salary DESC;',
    hint:'Use AVG(salary) and GROUP BY department.',
    validate: r => r.length > 0 && r.every(x => x.hasOwnProperty('avg_salary')) },

  { id:11, phase:1, week:3, title:'High-value departments', diff:'medium', topic:'HAVING',
    desc:'Show only departments where the average salary exceeds 80,000.',
    tables:['employees'],
    starter:'SELECT department, AVG(salary) AS avg_salary\nFROM employees\nGROUP BY department\n',
    solution:'SELECT department, AVG(salary) AS avg_salary FROM employees GROUP BY department HAVING AVG(salary) > 80000;',
    hint:'HAVING filters after GROUP BY. Use HAVING AVG(salary) > 80000.',
    validate: r => r.length > 0 && r.every(x => x.avg_salary > 80000) },

  { id:12, phase:1, week:4, title:'Products with low stock', diff:'easy', topic:'WHERE',
    desc:'Find all products where stock is less than 30. Show name, category, and stock.',
    tables:['products'],
    starter:'SELECT name, category, stock\nFROM products\nWHERE ',
    solution:'SELECT name, category, stock FROM products WHERE stock < 30 ORDER BY stock;',
    hint:'Filter with WHERE stock < 30.',
    validate: r => r.length > 0 && r.every(x => x.stock < 30) },

  { id:13, phase:2, week:5, title:'Orders with customer names', diff:'medium', topic:'JOIN',
    desc:'Show each order with the customer name. Include order id, order date, total, and customer name.',
    tables:['orders','customers'],
    starter:'SELECT o.id, o.order_date, o.total, c.name\nFROM orders o\n',
    solution:'SELECT o.id, o.order_date, o.total, c.name FROM orders o INNER JOIN customers c ON o.customer_id = c.id ORDER BY o.order_date;',
    hint:'INNER JOIN customers c ON o.customer_id = c.id links the two tables.',
    validate: r => r.length > 0 && r.every(x => x.hasOwnProperty('name')) },

  { id:14, phase:2, week:5, title:'Customers with no orders', diff:'medium', topic:'LEFT JOIN',
    desc:'Find customers who have never placed an order.',
    tables:['customers','orders'],
    starter:'SELECT c.name, c.email\nFROM customers c\n',
    solution:'SELECT c.name, c.email FROM customers c LEFT JOIN orders o ON c.id = o.customer_id WHERE o.id IS NULL;',
    hint:'LEFT JOIN keeps all customers. WHERE o.id IS NULL finds those with no matching order.',
    validate: r => r.length > 0 },

  { id:15, phase:2, week:5, title:'Order item details', diff:'medium', topic:'JOIN',
    desc:'Show each order item with the product name and category.',
    tables:['order_items','products'],
    starter:'SELECT oi.order_id, p.name, p.category, oi.qty, oi.unit_price\nFROM order_items oi\n',
    solution:'SELECT oi.order_id, p.name, p.category, oi.qty, oi.unit_price FROM order_items oi INNER JOIN products p ON oi.product_id = p.id;',
    hint:'JOIN products p ON oi.product_id = p.id.',
    validate: r => r.length > 0 && r.every(x => x.hasOwnProperty('name') && x.hasOwnProperty('category')) },

  { id:16, phase:2, week:5, title:'Top customers by spend', diff:'medium', topic:'JOIN',
    desc:'List the top 5 customers ranked by total amount spent. Show customer name and total spend.',
    tables:['customers','orders'],
    starter:'SELECT c.name, SUM(o.total) AS total_spend\nFROM customers c\nJOIN orders o ON c.id = o.customer_id\n',
    solution:'SELECT c.name, SUM(o.total) AS total_spend FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.name ORDER BY total_spend DESC LIMIT 5;',
    hint:'GROUP BY c.id, c.name and SUM(o.total), then ORDER BY total_spend DESC LIMIT 5.',
    validate: r => r.length === 5 },

  { id:17, phase:2, week:6, title:'Categorise products by price', diff:'medium', topic:'CASE WHEN',
    desc:"Label each product as 'Budget' (< $25), 'Mid-range' ($25–$100), or 'Premium' (> $100).",
    tables:['products'],
    starter:"SELECT name, price,\n  CASE\n    WHEN price < 25 THEN 'Budget'\n    \n  END AS price_tier\nFROM products;",
    solution:"SELECT name, price, CASE WHEN price < 25 THEN 'Budget' WHEN price <= 100 THEN 'Mid-range' ELSE 'Premium' END AS price_tier FROM products ORDER BY price;",
    hint:"Add WHEN price <= 100 THEN 'Mid-range' and ELSE 'Premium' to your CASE expression.",
    validate: r => r.length > 0 && r.every(x => x.hasOwnProperty('price_tier')) },

  { id:18, phase:2, week:6, title:'Orders by month', diff:'medium', topic:'DATE',
    desc:'Count orders per month. Show the month number and order count.',
    tables:['orders'],
    starter:"SELECT strftime('%m', order_date) AS month,\n  COUNT(*) AS order_count\nFROM orders\n",
    solution:"SELECT strftime('%m', order_date) AS month, COUNT(*) AS order_count FROM orders GROUP BY month ORDER BY month;",
    hint:"Use GROUP BY month to group by the extracted month.",
    validate: r => r.length > 0 && r.every(x => x.hasOwnProperty('order_count')) },

  { id:19, phase:2, week:6, title:'Employee salary bands', diff:'medium', topic:'CASE WHEN',
    desc:"Classify employees as 'Junior' (salary < 75k), 'Mid' (75k–90k), or 'Senior' (> 90k). Show name, salary, band.",
    tables:['employees'],
    starter:'SELECT name, salary,\n  CASE\n    WHEN salary < 75000 THEN \'Junior\'\n    \n  END AS band\nFROM employees;',
    solution:"SELECT name, salary, CASE WHEN salary < 75000 THEN 'Junior' WHEN salary <= 90000 THEN 'Mid' ELSE 'Senior' END AS band FROM employees ORDER BY salary;",
    hint:"Add WHEN salary <= 90000 THEN 'Mid' and ELSE 'Senior'.",
    validate: r => r.length > 0 && r.every(x => x.hasOwnProperty('band')) },

  { id:20, phase:2, week:7, title:'Customers who spent above average', diff:'medium', topic:'Subquery',
    desc:'Find customers whose total spend is above the average order total.',
    tables:['customers','orders'],
    starter:'SELECT c.name, SUM(o.total) AS total_spend\nFROM customers c\nJOIN orders o ON c.id = o.customer_id\nGROUP BY c.id, c.name\nHAVING total_spend > ',
    solution:'SELECT c.name, SUM(o.total) AS total_spend FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.name HAVING total_spend > (SELECT AVG(total) FROM orders);',
    hint:'Use (SELECT AVG(total) FROM orders) as the value to compare against in HAVING.',
    validate: r => r.length > 0 },

  { id:21, phase:2, week:7, title:'Most popular product category', diff:'medium', topic:'Subquery',
    desc:'Find the product category that appears most often in order_items (by total qty sold).',
    tables:['order_items','products'],
    starter:'SELECT p.category, SUM(oi.qty) AS total_qty\nFROM order_items oi\nJOIN products p ON oi.product_id = p.id\nGROUP BY p.category\n',
    solution:'SELECT p.category, SUM(oi.qty) AS total_qty FROM order_items oi JOIN products p ON oi.product_id = p.id GROUP BY p.category ORDER BY total_qty DESC LIMIT 1;',
    hint:'ORDER BY total_qty DESC LIMIT 1 gives the top category.',
    validate: r => r.length === 1 },

  { id:22, phase:2, week:7, title:'Sales above team average', diff:'hard', topic:'Subquery',
    desc:'Show each sale where the amount exceeds the average for that region.',
    tables:['sales'],
    starter:'SELECT s1.region, s1.amount, s1.sale_date\nFROM sales s1\nWHERE s1.amount > (\n  \n);',
    solution:'SELECT s1.region, s1.amount, s1.sale_date FROM sales s1 WHERE s1.amount > (SELECT AVG(s2.amount) FROM sales s2 WHERE s2.region = s1.region) ORDER BY s1.region, s1.amount DESC;',
    hint:'Use a correlated subquery: SELECT AVG(s2.amount) FROM sales s2 WHERE s2.region = s1.region',
    validate: r => r.length > 0 },

  { id:23, phase:2, week:8, title:'Three-table join', diff:'hard', topic:'JOIN',
    desc:'Show each order with customer name, product names, and quantities. Join customers, orders, order_items, and products.',
    tables:['customers','orders','order_items','products'],
    starter:'SELECT c.name AS customer, p.name AS product, oi.qty\nFROM orders o\n',
    solution:'SELECT c.name AS customer, p.name AS product, oi.qty FROM orders o JOIN customers c ON o.customer_id = c.id JOIN order_items oi ON oi.order_id = o.id JOIN products p ON oi.product_id = p.id ORDER BY c.name;',
    hint:'Chain three JOINs: orders → customers, orders → order_items → products.',
    validate: r => r.length > 0 && r.every(x => x.hasOwnProperty('customer') && x.hasOwnProperty('product')) },

  { id:24, phase:2, week:8, title:'Employee and their manager', diff:'medium', topic:'SELF JOIN',
    desc:'Show each employee with their manager name. Employees without a manager should still appear.',
    tables:['employees'],
    starter:'SELECT e.name AS employee, m.name AS manager\nFROM employees e\n',
    solution:'SELECT e.name AS employee, m.name AS manager FROM employees e LEFT JOIN employees m ON e.manager_id = m.id ORDER BY manager NULLS LAST;',
    hint:'LEFT JOIN employees m ON e.manager_id = m.id. Use LEFT JOIN so employees with no manager still show.',
    validate: r => r.length === 10 },

  { id:25, phase:3, week:9, title:'Top 3 products per category', diff:'hard', topic:'CTE',
    desc:'Using a CTE, find the top 3 most expensive products in each category.',
    tables:['products'],
    starter:'WITH ranked AS (\n  SELECT name, category, price,\n    ROW_NUMBER() OVER (PARTITION BY category ORDER BY price DESC) AS rn\n  FROM products\n)\nSELECT ',
    solution:'WITH ranked AS (SELECT name, category, price, ROW_NUMBER() OVER (PARTITION BY category ORDER BY price DESC) AS rn FROM products) SELECT name, category, price FROM ranked WHERE rn <= 3 ORDER BY category, price DESC;',
    hint:'Filter the CTE result with WHERE rn <= 3.',
    validate: r => r.length > 0 },

  { id:26, phase:3, week:9, title:'Monthly sales summary CTE', diff:'hard', topic:'CTE',
    desc:'Use a CTE to compute total sales per month, then show months where total exceeded 20,000.',
    tables:['sales'],
    starter:"WITH monthly AS (\n  SELECT strftime('%Y-%m', sale_date) AS month,\n    SUM(amount) AS total\n  FROM sales\n  GROUP BY month\n)\nSELECT ",
    solution:"WITH monthly AS (SELECT strftime('%Y-%m', sale_date) AS month, SUM(amount) AS total FROM sales GROUP BY month) SELECT month, total FROM monthly WHERE total > 20000 ORDER BY month;",
    hint:'Query the CTE with SELECT month, total FROM monthly WHERE total > 20000.',
    validate: r => r.length >= 0 },

  { id:27, phase:3, week:10, title:'Rank employees by salary', diff:'medium', topic:'Window',
    desc:'Add a rank to each employee based on salary (highest = rank 1). Show name, salary, and rank.',
    tables:['employees'],
    starter:'SELECT name, salary,\n  RANK() OVER (ORDER BY salary DESC) AS salary_rank\nFROM employees\n',
    solution:'SELECT name, salary, RANK() OVER (ORDER BY salary DESC) AS salary_rank FROM employees ORDER BY salary_rank;',
    hint:'RANK() OVER (ORDER BY salary DESC) assigns rank 1 to the highest salary.',
    validate: r => r.length === 10 && r[0].salary_rank === 1 },

  { id:28, phase:3, week:10, title:'Running total of sales', diff:'hard', topic:'Window',
    desc:'Show each sale with a running total of amount ordered by date.',
    tables:['sales'],
    starter:'SELECT sale_date, amount,\n  SUM(amount) OVER (ORDER BY sale_date) AS running_total\nFROM sales\n',
    solution:'SELECT sale_date, amount, SUM(amount) OVER (ORDER BY sale_date) AS running_total FROM sales ORDER BY sale_date;',
    hint:'SUM(amount) OVER (ORDER BY sale_date) accumulates amount as dates progress.',
    validate: r => r.length > 0 && r.every(x => x.hasOwnProperty('running_total')) },

  { id:29, phase:3, week:10, title:'Compare each sale to previous', diff:'hard', topic:'Window',
    desc:'Show each sale with the previous sale amount (LAG) and the difference.',
    tables:['sales'],
    starter:'SELECT employee_id, sale_date, amount,\n  LAG(amount) OVER (PARTITION BY employee_id ORDER BY sale_date) AS prev_sale,\n  \nFROM sales;',
    solution:'SELECT employee_id, sale_date, amount, LAG(amount) OVER (PARTITION BY employee_id ORDER BY sale_date) AS prev_sale, amount - LAG(amount) OVER (PARTITION BY employee_id ORDER BY sale_date) AS diff FROM sales ORDER BY employee_id, sale_date;',
    hint:'Subtract LAG(amount) OVER (...) from amount to get the difference.',
    validate: r => r.length > 0 },

  { id:30, phase:3, week:10, title:'Top seller per region', diff:'hard', topic:'Window',
    desc:'Find the employee with the highest total sales in each region.',
    tables:['sales','employees'],
    starter:'WITH totals AS (\n  SELECT e.name, s.region, SUM(s.amount) AS total,\n    RANK() OVER (PARTITION BY s.region ORDER BY SUM(s.amount) DESC) AS rk\n  FROM sales s\n  JOIN employees e ON s.employee_id = e.id\n  GROUP BY e.name, s.region\n)\nSELECT ',
    solution:'WITH totals AS (SELECT e.name, s.region, SUM(s.amount) AS total, RANK() OVER (PARTITION BY s.region ORDER BY SUM(s.amount) DESC) AS rk FROM sales s JOIN employees e ON s.employee_id = e.id GROUP BY e.name, s.region) SELECT name, region, total FROM totals WHERE rk = 1 ORDER BY region;',
    hint:'Filter WHERE rk = 1 from the CTE to get only the top-ranked per region.',
    validate: r => r.length > 0 },

  { id:31, phase:3, week:11, title:'Products never ordered', diff:'medium', topic:'JOIN',
    desc:'Find products that appear in no orders (never appear in order_items).',
    tables:['products','order_items'],
    starter:'SELECT p.name, p.category\nFROM products p\n',
    solution:'SELECT p.name, p.category FROM products p LEFT JOIN order_items oi ON p.id = oi.product_id WHERE oi.id IS NULL;',
    hint:'LEFT JOIN order_items and filter WHERE oi.id IS NULL.',
    validate: r => r.length > 0 },

  { id:32, phase:3, week:11, title:'Department headcount and payroll', diff:'medium', topic:'GROUP BY',
    desc:'For each department, show headcount, total payroll, and average salary rounded to 2 decimal places.',
    tables:['employees'],
    starter:'SELECT department,\n  COUNT(*) AS headcount,\n  \nFROM employees\nGROUP BY department;',
    solution:'SELECT department, COUNT(*) AS headcount, SUM(salary) AS total_payroll, ROUND(AVG(salary),2) AS avg_salary FROM employees GROUP BY department ORDER BY total_payroll DESC;',
    hint:'Use SUM(salary) for total_payroll and ROUND(AVG(salary),2) for avg_salary.',
    validate: r => r.length > 0 && r.every(x => x.hasOwnProperty('headcount') && x.hasOwnProperty('avg_salary')) },

  { id:33, phase:3, week:11, title:'UNION: all product and employee names', diff:'medium', topic:'UNION',
    desc:"Combine all product names (type='product') and employee names (type='employee') into one list.",
    tables:['products','employees'],
    starter:"SELECT name, 'product' AS type FROM products\n",
    solution:"SELECT name, 'product' AS type FROM products UNION ALL SELECT name, 'employee' AS type FROM employees ORDER BY type, name;",
    hint:"Use UNION ALL to combine both SELECTs. The second SELECT must have the same columns.",
    validate: r => r.length === 20 },

  { id:34, phase:4, week:12, title:'Customer lifetime value', diff:'hard', topic:'Analytics',
    desc:'For each customer, compute: total orders, total spend, average order value, and first order date. Order by total spend descending.',
    tables:['customers','orders'],
    starter:'SELECT c.name,\n  COUNT(o.id) AS total_orders,\n  \nFROM customers c\nJOIN orders o ON c.id = o.customer_id\nGROUP BY c.id, c.name\nORDER BY total_spend DESC;',
    solution:'SELECT c.name, COUNT(o.id) AS total_orders, ROUND(SUM(o.total),2) AS total_spend, ROUND(AVG(o.total),2) AS avg_order_value, MIN(o.order_date) AS first_order FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.name ORDER BY total_spend DESC;',
    hint:'Use SUM, AVG, MIN on order columns, grouped by customer.',
    validate: r => r.length > 0 && r.every(x => x.hasOwnProperty('total_orders') && x.hasOwnProperty('total_spend')) },

  { id:35, phase:4, week:12, title:'Month-over-month sales growth', diff:'hard', topic:'Analytics',
    desc:'Calculate monthly total sales and the percentage change from the prior month.',
    tables:['sales'],
    starter:"WITH monthly AS (\n  SELECT strftime('%Y-%m', sale_date) AS month, SUM(amount) AS total\n  FROM sales GROUP BY month\n)\nSELECT month, total,\n  LAG(total) OVER (ORDER BY month) AS prev_total,\n  \nFROM monthly;",
    solution:"WITH monthly AS (SELECT strftime('%Y-%m', sale_date) AS month, SUM(amount) AS total FROM sales GROUP BY month) SELECT month, total, LAG(total) OVER (ORDER BY month) AS prev_total, ROUND((total - LAG(total) OVER (ORDER BY month)) * 100.0 / LAG(total) OVER (ORDER BY month), 1) AS pct_change FROM monthly ORDER BY month;",
    hint:'(total - prev) * 100.0 / prev gives the percentage change. Wrap in ROUND(...,1).',
    validate: r => r.length > 0 },

  { id:36, phase:4, week:12, title:'Full analyst dashboard query', diff:'hard', topic:'Analytics',
    desc:'In one query: for each region, show total sales, top month by sales, and number of sales reps.',
    tables:['sales','employees'],
    starter:'WITH reg_stats AS (\n  SELECT region, SUM(amount) AS total, COUNT(DISTINCT employee_id) AS reps\n  FROM sales GROUP BY region\n),\nbest_month AS (\n  SELECT region,\n    strftime(\'%Y-%m\', sale_date) AS month,\n    SUM(amount) AS month_total,\n    RANK() OVER (PARTITION BY region ORDER BY SUM(amount) DESC) AS rk\n  FROM sales GROUP BY region, month\n)\nSELECT ',
    solution:"WITH reg_stats AS (SELECT region, SUM(amount) AS total, COUNT(DISTINCT employee_id) AS reps FROM sales GROUP BY region), best_month AS (SELECT region, strftime('%Y-%m', sale_date) AS month, SUM(amount) AS month_total, RANK() OVER (PARTITION BY region ORDER BY SUM(amount) DESC) AS rk FROM sales GROUP BY region, month) SELECT r.region, r.total, r.reps, b.month AS best_month, b.month_total FROM reg_stats r JOIN best_month b ON r.region = b.region WHERE b.rk = 1 ORDER BY r.total DESC;",
    hint:'JOIN reg_stats r with best_month b ON r.region = b.region WHERE b.rk = 1.',
    validate: r => r.length > 0 && r.every(x => x.hasOwnProperty('region') && x.hasOwnProperty('total')) },
];